"""add weather tables

Revision ID: 20251211_add_weather_tables
Revises: <previous_revision_id>
Create Date: 2025-12-11 19:15:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20251211_add_weather_tables"
down_revision = None  # replace with actual previous revision id if exists
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "region",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
    )
    op.create_table(
        "weather_daily",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("region_id", sa.Integer(), sa.ForeignKey("region.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("tmin", sa.Float(), nullable=True),
        sa.Column("tmax", sa.Float(), nullable=True),
        sa.Column("tavg", sa.Float(), nullable=True),
        sa.Column("precipitation", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_daily")
    op.drop_table("region")
    # ### end Alembic commands ###
