"""add crop forecast alert tables

Revision ID: 20251211_add_core_tables
Revises: 20251211_add_yield_history
Create Date: 2025-12-11 20:00:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "20251211_add_core_tables"
down_revision = "20251211_add_yield_history"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_crop_code"), "crop", ["code"], unique=True)
    op.create_index(op.f("ix_crop_id"), "crop", ["id"], unique=False)
    
    op.create_table(
        "forecast",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("region_id", sa.Integer(), sa.ForeignKey("region.id"), nullable=False),
        sa.Column("crop_id", sa.Integer(), sa.ForeignKey("crop.id"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("yield_index", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index(op.f("ix_forecast_id"), "forecast", ["id"], unique=False)

    op.create_table(
        "alert",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("region_id", sa.Integer(), sa.ForeignKey("region.id"), nullable=False),
        sa.Column("crop_id", sa.Integer(), sa.ForeignKey("crop.id"), nullable=True),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(op.f("ix_alert_id"), "alert", ["id"], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_id"), table_name="alert")
    op.drop_table("alert")
    op.drop_index(op.f("ix_forecast_id"), table_name="forecast")
    op.drop_table("forecast")
    op.drop_index(op.f("ix_crop_id"), table_name="crop")
    op.drop_index(op.f("ix_crop_code"), table_name="crop")
    op.drop_table("crop")
    # ### end Alembic commands ###
