"""add yield_history table

Revision ID: 20251211_add_yield_history
Revises: 20251211_add_weather_tables
Create Date: 2025-12-11 19:55:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20251211_add_yield_history"
down_revision = "20251211_add_weather_tables"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "yield_history",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("region_id", sa.Integer(), sa.ForeignKey("region.id"), nullable=False),
        sa.Column("crop", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("date_harvest", sa.Date(), nullable=False),
        sa.Column("yield_value", sa.Float(), nullable=False),
        sa.Column("yield_index", sa.Float(), nullable=False),
    )
    op.create_index(op.f("ix_yield_history_id"), "yield_history", ["id"], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_yield_history_id"), table_name="yield_history")
    op.drop_table("yield_history")
    # ### end Alembic commands ###
