"""add_forecast_enrichment_and_climatology

Revision ID: 23544eb8ea12
Revises: cc8d885dbd03
Create Date: 2025-12-13 18:00:50.820988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23544eb8ea12'
down_revision = 'cc8d885dbd03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climatology_daily',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('day_of_year', sa.Integer(), nullable=False),
    sa.Column('tmin_c', sa.Float(), nullable=True),
    sa.Column('tmax_c', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('std_t', sa.Float(), nullable=True),
    sa.Column('std_r', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('region_id', 'day_of_year')
    )
    op.create_index(op.f('ix_climatology_daily_day_of_year'), 'climatology_daily', ['day_of_year'], unique=False)
    op.create_index(op.f('ix_climatology_daily_region_id'), 'climatology_daily', ['region_id'], unique=False)
    op.create_table('yield_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date_harvest', sa.Date(), nullable=False),
    sa.Column('yield_value', sa.Float(), nullable=False),
    sa.Column('yield_index', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yield_history_id'), 'yield_history', ['id'], unique=False)
    op.create_index(op.f('ix_crop_code'), 'crop', ['code'], unique=True)
    op.create_index(op.f('ix_crop_id'), 'crop', ['id'], unique=False)
    op.add_column('forecast', sa.Column('tmin_c', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('tmax_c', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('tmean_c', sa.Float(), nullable=True))
    op.add_column('forecast', sa.Column('source', sa.String(length=30), server_default='api', nullable=False))
    op.add_column('forecast', sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('forecast', sa.Column('model_version', sa.String(length=30), nullable=True))
    op.create_unique_constraint('uix_forecast_region_crop_date', 'forecast', ['region_id', 'crop_id', 'date'])
    op.create_index(op.f('ix_region_id'), 'region', ['id'], unique=False)
    op.create_index(op.f('ix_weather_daily_id'), 'weather_daily', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_daily_id'), table_name='weather_daily')
    op.drop_index(op.f('ix_region_id'), table_name='region')
    op.drop_constraint('uix_forecast_region_crop_date', 'forecast', type_='unique')
    op.drop_column('forecast', 'model_version')
    op.drop_column('forecast', 'fetched_at')
    op.drop_column('forecast', 'source')
    op.drop_column('forecast', 'tmean_c')
    op.drop_column('forecast', 'tmax_c')
    op.drop_column('forecast', 'tmin_c')
    op.drop_index(op.f('ix_crop_id'), table_name='crop')
    op.drop_index(op.f('ix_crop_code'), table_name='crop')
    op.drop_index(op.f('ix_yield_history_id'), table_name='yield_history')
    op.drop_table('yield_history')
    op.drop_index(op.f('ix_climatology_daily_region_id'), table_name='climatology_daily')
    op.drop_index(op.f('ix_climatology_daily_day_of_year'), table_name='climatology_daily')
    op.drop_table('climatology_daily')
    # ### end Alembic commands ###
