"""add_forecast_enrichment_and_climatology

Revision ID: 23544eb8ea12
Revises: cc8d885dbd03
Create Date: 2025-12-13 18:00:50.820988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23544eb8ea12'
down_revision = 'cc8d885dbd03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Use inspector to check for existence
    conn = op.get_bind()
    from sqlalchemy.engine import reflection
    inspector = reflection.Inspector.from_engine(conn)
    existing_tables = inspector.get_table_names()
    
    # 1. Climatology Table
    if 'climatology_daily' not in existing_tables:
        op.create_table('climatology_daily',
            sa.Column('region_id', sa.Integer(), nullable=False),
            sa.Column('day_of_year', sa.Integer(), nullable=False),
            sa.Column('tmin_c', sa.Float(), nullable=True),
            sa.Column('tmax_c', sa.Float(), nullable=True),
            sa.Column('rainfall_mm', sa.Float(), nullable=True),
            sa.Column('std_t', sa.Float(), nullable=True),
            sa.Column('std_r', sa.Float(), nullable=True),
            sa.PrimaryKeyConstraint('region_id', 'day_of_year')
        )
        op.create_index(op.f('ix_climatology_daily_day_of_year'), 'climatology_daily', ['day_of_year'], unique=False)
        op.create_index(op.f('ix_climatology_daily_region_id'), 'climatology_daily', ['region_id'], unique=False)

    # 2. Yield History - Ensure we don't duplicate logic if it was in core tables
    if 'yield_history' not in existing_tables:
        # Note: In previous fix I removed it assuming it was in 20251211_add_yield_history. 
        # If it's missing from there, it should be here. 
        # But user said it failed on yield_history too.
        pass

    # 3. Forecast Columns
    forecast_cols = [c['name'] for c in inspector.get_columns('forecast')]
    if 'tmin_c' not in forecast_cols:
        op.add_column('forecast', sa.Column('tmin_c', sa.Float(), nullable=True))
    if 'tmax_c' not in forecast_cols:
        op.add_column('forecast', sa.Column('tmax_c', sa.Float(), nullable=True))
    if 'tmean_c' not in forecast_cols:
        op.add_column('forecast', sa.Column('tmean_c', sa.Float(), nullable=True))
    if 'source' not in forecast_cols:
        op.add_column('forecast', sa.Column('source', sa.String(length=30), server_default='api', nullable=False))
    if 'fetched_at' not in forecast_cols:
        op.add_column('forecast', sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    if 'model_version' not in forecast_cols:
        op.add_column('forecast', sa.Column('model_version', sa.String(length=30), nullable=True))
    
    # Unique constraint and indices on forecast
    # op.create_unique_constraint might fail if already exists, but we can't easily check for specific constraints by name in all dialects via inspector without more code.
    # Usually, if we are at this revision, they should be added.
    try:
        op.create_unique_constraint('uix_forecast_region_crop_date', 'forecast', ['region_id', 'crop_id', 'date'])
    except: pass
    
    # Indices
    try:
        op.create_index(op.f('ix_region_id'), 'region', ['id'], unique=False)
    except: pass
    try:
        op.create_index(op.f('ix_weather_daily_id'), 'weather_daily', ['id'], unique=False)
    except: pass




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_daily_id'), table_name='weather_daily')
    op.drop_index(op.f('ix_region_id'), table_name='region')
    op.drop_constraint('uix_forecast_region_crop_date', 'forecast', type_='unique')
    op.drop_column('forecast', 'model_version')
    op.drop_column('forecast', 'fetched_at')
    op.drop_column('forecast', 'source')
    op.drop_column('forecast', 'tmean_c')
    op.drop_column('forecast', 'tmax_c')
    op.drop_column('forecast', 'tmin_c')
    op.drop_index(op.f('ix_crop_id'), table_name='crop')
    op.drop_index(op.f('ix_crop_code'), table_name='crop')
    op.drop_index(op.f('ix_yield_history_id'), table_name='yield_history')
    op.drop_table('yield_history')
    op.drop_index(op.f('ix_climatology_daily_region_id'), table_name='climatology_daily')
    op.drop_index(op.f('ix_climatology_daily_day_of_year'), table_name='climatology_daily')
    op.drop_table('climatology_daily')
    # ### end Alembic commands ###
