"""add_seasonal_yield_tables

Revision ID: 3ad0f54d93d3
Revises: 9a62f3c122c8
Create Date: 2025-12-20 22:25:23.723237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad0f54d93d3'
down_revision = '9a62f3c122c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquacrop_sim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('simulated_yield_t_ha', sa.Float(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'crop_id', 'season_year', name='uix_aquacrop_sim_region_crop_year')
    )
    op.create_index(op.f('ix_aquacrop_sim_id'), 'aquacrop_sim', ['id'], unique=False)
    op.create_table('ndvi_timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ndvi', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndvi_timeseries_id'), 'ndvi_timeseries', ['id'], unique=False)
    op.create_table('season_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'crop_id', 'season_year', name='uix_season_calendar_region_crop_year')
    )
    op.create_index(op.f('ix_season_calendar_id'), 'season_calendar', ['id'], unique=False)
    op.create_table('yield_observed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('yield_t_ha', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'crop_id', 'season_year', name='uix_yield_observed_region_crop_year')
    )
    op.create_index(op.f('ix_yield_observed_id'), 'yield_observed', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yield_observed_id'), table_name='yield_observed')
    op.drop_table('yield_observed')
    op.drop_index(op.f('ix_season_calendar_id'), table_name='season_calendar')
    op.drop_table('season_calendar')
    op.drop_index(op.f('ix_ndvi_timeseries_id'), table_name='ndvi_timeseries')
    op.drop_table('ndvi_timeseries')
    op.drop_index(op.f('ix_aquacrop_sim_id'), table_name='aquacrop_sim')
    op.drop_table('aquacrop_sim')
    # ### end Alembic commands ###
