"""update_climatology_daily_structure

Revision ID: 9a62f3c122c8
Revises: 23544eb8ea12
Create Date: 2025-12-20 19:35:59.735616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a62f3c122c8'
down_revision = '23544eb8ea12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climatology_daily', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_climatology_daily_id'), 'climatology_daily', ['id'], unique=False)
    op.create_unique_constraint('uix_climatology_region_doy', 'climatology_daily', ['region_id', 'day_of_year'])
    op.create_foreign_key(None, 'climatology_daily', 'region', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'climatology_daily', type_='foreignkey')
    op.drop_constraint('uix_climatology_region_doy', 'climatology_daily', type_='unique')
    op.drop_index(op.f('ix_climatology_daily_id'), table_name='climatology_daily')
    op.drop_column('climatology_daily', 'id')
    # ### end Alembic commands ###
